name: devel

on:
  push:
    paths:
      - "**.cpp"
      - "**.h"
      - "**meson**"
  pull_request:
    paths:
      - "**.cpp"
      - "**.h"
      - "**meson**"
  workflow_dispatch:

jobs:

  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - run: pip install meson ninja
    - run: meson setup builddir/
      env:
        CC: g++
    - run: meson compile -C builddir/
    - uses: actions/upload-artifact@v1
      with:
        name: Meson_Builddir
        path: builddir/

